= Файловый сервер

== Сервер

Сервер отправляет клиенту файлы по запросу.
Файлы лежат у сервера в `resources`.

При подключении клиента:

. Сервер отправляет список доступных файлов
. Клиент отправляет серверу имя выбранного файла
. Сервер отправляет содержимое файла
.. Если файла нет, сервер закрывает соединение с клиентом
. Сервер заново отправляет список доступных файлов

Сервер работает до тех пор, пока пользователь не введёт команду «exit».

=== Пример взаимодействия с пользователем

[source,text]
----
$ ./server.sh

Сервер запущен, порт 8888.
Для выхода введите «exit»

> exit
Сервер остановлен
----

== Клиент

При запуске клиент подключается к серверу.

Параметры командной строки:

. Адрес сервера
. Порт сервера
. Директория для сохранения файлов

После запуска:

. Клиент получает список файлов и выводит его пользователю
. Пользователь выбирает файл для скачивания
. Клиент отправляет запрос серверу и скачивает файл в директорию из аргументов командной строки

Для выхода из программы клиент вводит команду «exit»

=== Пример взаимодействия с пользователем

[source,text]
----
$ ./client.sh 1.1.1.1 8888 /tmp/

Соединение установлено.
Список файлов:

1. photo.jpg
2. music.mp3
3. bear.png

Выберите файл для скачивания:

> 1

Файл «photo.jpg» скачан в /tmp/photo.jpg

Список файлов:

1. photo.jpg
2. music.mp3
3. bear.png

> exit
До свидания
----

== Требования к проекту

. maven-проект с двумя модулями: для клиента и сервера
. В каждом модуле -- `module-info.java`
. Для каждого приложения -- скрипт для запуска
